### ISSUE TITLE
Add support for other project types

### ISSUE THREAD

**Issue by antonmedv** [juliangruber/travis-watch#15]
For example for PHP projects.

**Comment by juliangruber** [comment]
This for example now works with the Symfony project as well:

![screen shot 2017-03-24 at 08 05 59](https://cloud.githubusercontent.com/assets/10247/24283964/fa5acd94-1068-11e7-89d0-ca4ae1c1389a.png)

Feel free to open more issues for different build environments :)

**Comment by antonmedv** [comment]
Got this on https://github.com/deployphp/deployer
```
$ travis-watch
module.js:472
    throw err;
    ^

Error: Cannot find module '/Users/anton/Projects/deployer/package.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/travis-watch/index.js:19:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by juliangruber** [comment]
oh sorry, you need to upgrade your cli first:

```bash
$ npm install -g travis-watch@latest
```

**Comment by antonmedv** [comment]
Now working, but:
```
$ travis-watch --help
child_process.js:524
    throw err;
    ^

Error: spawnSync /bin/sh ENOENT
    at exports._errnoException (util.js:1034:11)
    at spawnSync (child_process.js:459:20)
    at Object.execSync (child_process.js:515:13)
    at module.exports.sync.dir (/usr/local/lib/node_modules/travis-watch/node_modules/git-current-commit/index.js:17:6)
    at Object.<anonymous> (/usr/local/lib/node_modules/travis-watch/index.js:16:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by juliangruber** [comment]
there's no `--help` yet, I added an issue here https://github.com/juliangruber/travis-watch/issues/27

**Comment by antonmedv** [comment]
But throw error with call stack is bad DX.

**Comment by juliangruber** [comment]
goot point, i'll add a more meaningful error message in that case

**Comment by juliangruber** [comment]
the latest version now also prints a nice error here
